[package]
name = "filesparse"
version = "0.0.1"
edition = "2021"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["ioapiset", "winioctl", "errhandlingapi", "fileapi"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.143"
